/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as RolamRouteImport } from './routes/rolam'
import { Route as PublikaciokRouteImport } from './routes/publikaciok'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as InformaciokRouteImport } from './routes/informaciok'
import { Route as AszfRouteImport } from './routes/aszf'
import { Route as IndexRouteImport } from './routes/index'

const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const RolamRoute = RolamRouteImport.update({
  id: '/rolam',
  path: '/rolam',
  getParentRoute: () => rootRouteImport,
} as any)
const PublikaciokRoute = PublikaciokRouteImport.update({
  id: '/publikaciok',
  path: '/publikaciok',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const InformaciokRoute = InformaciokRouteImport.update({
  id: '/informaciok',
  path: '/informaciok',
  getParentRoute: () => rootRouteImport,
} as any)
const AszfRoute = AszfRouteImport.update({
  id: '/aszf',
  path: '/aszf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aszf': typeof AszfRoute
  '/informaciok': typeof InformaciokRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/publikaciok': typeof PublikaciokRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aszf': typeof AszfRoute
  '/informaciok': typeof InformaciokRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/publikaciok': typeof PublikaciokRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aszf': typeof AszfRoute
  '/informaciok': typeof InformaciokRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/publikaciok': typeof PublikaciokRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aszf'
    | '/informaciok'
    | '/kapcsolat'
    | '/publikaciok'
    | '/rolam'
    | '/szolgaltatasok'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aszf'
    | '/informaciok'
    | '/kapcsolat'
    | '/publikaciok'
    | '/rolam'
    | '/szolgaltatasok'
  id:
    | '__root__'
    | '/'
    | '/aszf'
    | '/informaciok'
    | '/kapcsolat'
    | '/publikaciok'
    | '/rolam'
    | '/szolgaltatasok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AszfRoute: typeof AszfRoute
  InformaciokRoute: typeof InformaciokRoute
  KapcsolatRoute: typeof KapcsolatRoute
  PublikaciokRoute: typeof PublikaciokRoute
  RolamRoute: typeof RolamRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolam': {
      id: '/rolam'
      path: '/rolam'
      fullPath: '/rolam'
      preLoaderRoute: typeof RolamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publikaciok': {
      id: '/publikaciok'
      path: '/publikaciok'
      fullPath: '/publikaciok'
      preLoaderRoute: typeof PublikaciokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informaciok': {
      id: '/informaciok'
      path: '/informaciok'
      fullPath: '/informaciok'
      preLoaderRoute: typeof InformaciokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aszf': {
      id: '/aszf'
      path: '/aszf'
      fullPath: '/aszf'
      preLoaderRoute: typeof AszfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AszfRoute: AszfRoute,
  InformaciokRoute: InformaciokRoute,
  KapcsolatRoute: KapcsolatRoute,
  PublikaciokRoute: PublikaciokRoute,
  RolamRoute: RolamRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
